# Installed Packages Management
base_packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - htop
  - iotop
  - software-properties-common
  - python3
  - python3-pip
  - sl
  - vim

# Authorized Keys Management
authorized_keys: []

# Shell config
base_shell: '.bashrc'
base_shell_block: |
    # Vim aliases
    alias svim='sudo -E vim'

    # Docker aliases
    alias docker-rm-all='docker rm -f $(docker ps -aq)'
    alias docker-prune-all='docker container prune -f && docker image prune -f'
