# Installed Packages Management
base_packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - htop
  - iotop
  - software-properties-common
  - python3
  - python3-pip
  - sl
  - vim
