# Check the banner sudo /usr/sbin/update-motd
- name: Beaufiful Banner | Ensure necessary packages installed for beautiful banner
  ansible.builtin.apt:
    name:
      - figlet
      - toilet
    state: present

- name: Beaufiful Banner | Configure the motd.d file to 00-custom-header
  ansible.builtin.template:
    src: "00-custom-header.j2"
    dest: "/etc/update-motd.d/00-custom-header"
    owner: root
    mode: "0755"

- name: Beaufiful Banner | Configure the motd.d file 99-ansible-info
  ansible.builtin.template:
    src: "99-ansible-info.j2"
    dest: "/etc/update-motd.d/99-ansible-info"
    owner: root
    mode: "0755"

- name: Beaufiful Banner | Disable motd.d files to don't show them in banner
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: file
    owner: root
    mode: "0644"
  ignore_errors: true
  with_items:
    - 10-uname

- name: Beaufiful Banner | Disable default MOTD message
  ansible.builtin.file:
    path: /etc/motd
    state: absent

# The programs included with the Debian GNU/Linux system are free software;
# the exact distribution terms for each program are described in the
# individual files in /usr/share/doc/*/copyright.

# Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
# permitted by applicable law.
