- name: Keys | Ensure users authorized keys set up
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.pubkey }}"
    state: present
  with_items: "{{ base_authorized_keys }}"

- name: Keys | Enable PubkeyAuthentication setting in sshd_config # By default it is disabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication\s+'
    line: 'PubkeyAuthentication yes'
    state: present
  notify: Restart sshd

- name: Keys | Disable PasswordAuthentication setting in sshd_config # By default it is enabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication\s+'
    line: 'PasswordAuthentication no'
    state: present
  when: base_disable_pass_auth
  notify: Restart sshd
