- hosts: raspberrypi
  become: yes
  
  vars:
    docker_enabled: true
  
  vars_files:
    - ../general_vars.yml
    - ../vault.yml
  
  # tasks:
  #   - name: Debug test_var
  #     debug:
  #       var: test_var
  
  roles:
    - "roles/config-services"
