- name: Playbook to configure basic services on Raspberry Pi
  hosts: raspberrypi
  become: true

  vars:
    base_docker_enabled: true
    config_services_fail2ban_enabled: true

  vars_files:
    - ../vault.yaml

  # tasks:
  #   - name: Debug test_var
  #     debug:
  #       var: test_var

  roles:
    - "roles/config_services"
